### PR TITLE
[Claims] Add act to claims

### PR DESCRIPTION
**Pull request by kageiit**
Updated `act` to reflect the documentation

### CODE REVIEW

**Review by DarrenBaldwin07 — COMMENTED** [review]
Hmm this is odd. When decoding a session token for cloud.tembo.io (for example) the payload looks like this:
```json
{
  "azp": "https://cloud.tembo.io",
  "exp": 1722819750,
  "iat": 1722733350,
  "iss": "https://clerk.tembo.io",
  "jti": "575bd5797db3da1dc5b9",
  "nbf": 1722733345,
  "org_id": "org_2jyEOHrzo8RWGERumZ61dghllsP",
  "org_role": "admin",
  "org_slug": "darrenbaldwin1",
...
}
```

So it does not seem like they should be nested like this PR. I have seen issues in the past where the session token claims are different based on when you created you app in Clerk

**Comment by kageiit** [comment]
Let me get in touch with clerk support and revisit this.

It's odd that we are seeing different claims


If it's due to some legacy behavior,

I can add some logic to deaerialzie from whichever exists in the payload

**Comment by DarrenBaldwin07** [comment]
> Let me get in touch with clerk support and revisit this.
> 
> It's odd that we are seeing different claims
> 
> If it's due to some legacy behavior,
> 
> I can add some logic to deaerialzie from whichever exists in the payload

I pinged my contact at Clerk too - will let ya know what I hear

**Comment by kageiit** [comment]
We double checked. the fields are nested at the right level on main branch. We had a custom jwt template that casued some confusion.

Ill update the PR to just do the actor change

**Review by DarrenBaldwin07 — APPROVED** [review]

**Pull request merged**
