### PR TITLE
[Claims] Add all possible backend claims to ClerkJWT

### PR DESCRIPTION
**Pull request by kageiit**
According to the clerk docs - https://clerk.com/docs/backend-requests/resources/session-tokens

There are additional claims in the JWT token for backend requests that can be useful to glean information about the user's active organization and permissions.

Implementation inspired from the official clerk go sdk - https://github.com/clerk/clerk-sdk-go/blob/3411ef39ca0f1f01a91fd6fa766c032d2f9683a9/clerk/session_claims.go#L16

Updated the unit tests to reflect the new claims

Related to #52

### CODE REVIEW

**Review by DarrenBaldwin07 — APPROVED** [review]
TY LGTM! Will include in 0.3.2 release (likely in a couple weeks)

**Comment by aarondemolder** [comment]
Also related to #52 I could see that adding custom claims here generally would be valuable - it does not look like it was included in these PRs? Is this planned?

**Comment by kageiit** [comment]
> Also related to #52 I could see that adding custom claims here generally would be valuable - it does not look like it was included in these PRs? Is this planned?

I added support in https://github.com/DarrenBaldwin07/clerk-rs/pull/63

This should be useful for additional fields in custom templates

**Comment by aarondemolder** [comment]
@kageiit fantastic! Thanks for doing so so quickly

**Pull request merged**
